---
- name: setup calico
  hosts: node01
  become: yes
  tasks:
  - name: Copy file1
    copy:
      src: install_calico_step1.yml
      dest: /root/install_calico_step1.yml
  - name: Copy file2
    copy:
      src: install_calico_step2.yml
      dest: /root/install_calico_step2.yml
  - name: install_calico_step1
    command: kubectl create -f /root/install_calico_step1.yml
  - name: install_calico_step2
    command: kubectl create -f /root/install_calico_step2.yml

