---
- name: Install ssh key
  hosts: ssh-copy
  tasks:
  - name: Install Key ...
    authorized_key:
      user: ubuntu
      state: present
      key: "{{lookup('file','/home/ubuntu/.ssh/id_rsa.pub')}}"
