---
- name: only ssh key auth
  hosts: nodes
  become: yes
  tasks:
  - name: EOF sshd_conf
    lineinfile:
      dest: /etc/ssh/sshd_config
      regexp: '^#?\s*PasswordAuthentication\s'
      line: 'PasswordAuthentication no'
      state: present
  - name: restart sshd service
    service:
      name: sshd
      state: restarted
